name: build and release and upload assets
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-jar:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt assembly
      - run: mv target/scala-2.13/cliche-assembly*.jar cliche.jar
      - uses: actions/upload-artifact@v3
        with:
          path: cliche.jar
          name: cliche.jar
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: cliche.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}

  build-linux-native-image:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: GRAALVM_HOME=$GRAALVM_11_ROOT sbt nativeImage
      - uses: actions/upload-artifact@v3
        with:
          path: target/native-image/cliche
          name: cliche-linux.bin
      - run: mv target/native-image/cliche ./
      - run: tar -czf cliche-linux.bin.tar.gz cliche
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: cliche-linux.bin.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}

  build-mac-native-image:
    runs-on: macos-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: $GRAALVM_11_ROOT/gu install native-image
      - run: GRAALVM_HOME=$GRAALVM_11_ROOT/../ sbt nativeImage
      - uses: actions/upload-artifact@v3
        with:
          path: target/native-image/cliche
          name: cliche-macos.bin
      - run: mv target/native-image/cliche ./
      - run: tar -czf cliche-macos.bin.tar.gz cliche
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: cliche-macos.bin.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
